// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC35CrYst4qBBbYL44y-goTNZnFpYytoP0',
    appId: '1:880068296315:web:18b0e3eb317049b39eecde',
    messagingSenderId: '880068296315',
    projectId: 'nuwakakaramdb',
    authDomain: 'nuwakakaramdb.firebaseapp.com',
    storageBucket: 'nuwakakaramdb.appspot.com',
    measurementId: 'G-0MJ25VT9KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKp7E5cwhE9EprB0IIQ47f-yMP6XCCok',
    appId: '1:880068296315:android:ecc53c460b1ce29c9eecde',
    messagingSenderId: '880068296315',
    projectId: 'nuwakakaramdb',
    storageBucket: 'nuwakakaramdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5CZLgqh86QGiFVF7eHJNfvdn-4-ueIU',
    appId: '1:880068296315:ios:eed5ef705d6c64529eecde',
    messagingSenderId: '880068296315',
    projectId: 'nuwakakaramdb',
    storageBucket: 'nuwakakaramdb.appspot.com',
    iosClientId: '880068296315-vahvq27q4bkjkjfh2m4t5vt9ir3npou9.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawa1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5CZLgqh86QGiFVF7eHJNfvdn-4-ueIU',
    appId: '1:880068296315:ios:76fbce8d336d7ae49eecde',
    messagingSenderId: '880068296315',
    projectId: 'nuwakakaramdb',
    storageBucket: 'nuwakakaramdb.appspot.com',
    iosClientId: '880068296315-sqqta0om5nguc0pq0os7m9hosu8dh14v.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawa1.RunnerTests',
  );
}
